# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kcvijay
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: remix-express-lambda
service: remix-express-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any

plugins:
  - serverless-offline

package:
  exclude:
    - .gitignore
    - .git/**